# Version of the configuration file
version: 5.1.0
# Icarus theme variant, can be "default" or "cyberpunk"
variant: default
# Path or URL to the website's logo
logo: /img/logo.svg
# Page metadata configurations
head:
    # URL or path to the website's icon
    favicon: /img/favicon.svg
    # Web application manifests configuration
    # https://developer.mozilla.org/en-US/docs/Web/Manifest
    manifest:
        # Name of the web application (default to the site title)
        name: RiverBreaker's blog
        # The displayed name of the web application
        # when there is not enough space to display full name
        short_name: RiverBreaker
        # The start URL of the web application
        start_url: 
        # The default theme color for the application
        theme_color: '#1E1E1E'
        # A placeholder background color for the application page to display
        # before its stylesheet is loaded
        background_color: '#252526'
        # The preferred display mode for the website
        display: standalone
        # Image files that can serve as application icons for different contexts
        icons:
            -
                # The path to the image file
                src: ''
                # A string containing space-separated image dimensions
                sizes: ''
                # A hint as to the media type of the image
                type: 
    # Open Graph metadata
    # https://hexo.io/docs/helpers.html#open-graph
    open_graph:
        # Page title (og:title) (optional)
        # You should leave this blank for most of the time
        title: 
        # Page type (og:type) (optional)
        # You should leave this blank for most of the time
        type: blog
        # Page URL (og:url) (optional)
        # You should leave this blank for most of the time
        url: 
        # Page cover (og:image) (optional)
        # You should leave this blank for most of the time
        image: 
        # Site name (og:site_name) (optional)
        # You should leave this blank for most of the time
        site_name: 
        # Page author (article:author) (optional)
        # You should leave this blank for most of the time
        author: 
        # Page description (og:description) (optional)
        # You should leave this blank for most of the time
        description: 
        # Twitter card type (twitter:card)
        twitter_card: 
        # Twitter ID (twitter:creator)
        twitter_id: 
        # Twitter Site (twitter:site)
        twitter_site: 
        # Google+ profile link (deprecated)
        google_plus: 
        # Facebook admin ID
        fb_admins: 
        # Facebook App ID
        fb_app_id: 
    # Structured data of the page
    # https://developers.google.com/search/docs/guides/intro-structured-data
    structured_data:
        # Page title (optional)
        # You should leave this blank for most of the time
        title: 
        # Page description (optional)
        # You should leave this blank for most of the time
        description: 
        # Page URL (optional)
        # You should leave this blank for most of the time
        url: 
        # Page author (article:author) (optional)
        # You should leave this blank for most of the time
        author: 
        # Page publisher (optional)
        # You should leave this blank for most of the time
        publisher: 
        # Page publisher logo (optional)
        # You should leave this blank for most of the time
        publisher_logo: 
        # Page images (optional)
        # You should leave this blank for most of the time
        image: 
    # Additional HTML meta tags in an array
    meta:
        # Meta tag specified in <attribute>=<value> style
        # E.g., name=theme-color;content=#123456 => <meta name="theme-color" content="123456">
        - 'name=theme-color;content=#123456'
    # URL or path to the website's RSS atom.xml
    rss: 
# Page top navigation bar configurations
navbar:
    # Navigation menu items
    menu:
        首页: /
        归档: /archives
        分类: /categories
        标签: /tags
        关于: /about
    # Links to be shown on the right of the navigation bar
    links:
        Download on GitHub:
            icon: fab fa-github
            url: https://github.com/RiverBreaker/RiverBreaker-blog
# Page footer configurations
footer:
    # Copyright text
    copyright: © 2024 RiverBreaker ❄️
    # Links to be shown on the right of the footer section
    links:
        Creative Commons:
            icon: fab fa-creative-commons
            url: https://creativecommons.org/
        Attribution 4.0 International:
            icon: fab fa-creative-commons-by
            url: https://creativecommons.org/licenses/by/4.0/
        Download on GitHub:
            icon: fab fa-github
            url: https://github.com/ppoffice/hexo-theme-icarus
# Article related configurations
article:
    # Code highlight settings
    highlight:
        # Code highlight themes
        # https://github.com/highlightjs/highlight.js/tree/master/src/styles
        theme: atom-one-light
        # Show copy code button
        clipboard: true
        # Default folding status of the code blocks. Can be "", "folded", "unfolded"
        fold: unfolded
    # Whether to show estimated article reading time
    readtime: true
    # Whether to show updated time. For "auto", shows article update time only when page.updated is set and it is different from page.date
    update_time: true
    # Article licensing block
    licenses:
        Creative Commons:
            icon: fab fa-creative-commons
            url: https://creativecommons.org/
        Attribution:
            icon: fab fa-creative-commons-by
            url: https://creativecommons.org/licenses/by/4.0/
        Noncommercial:
            icon: fab fa-creative-commons-nc
            url: https://creativecommons.org/licenses/by-nc/4.0/
# Search plugin configurations
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Search/
# 搜索引擎：
search:
    type: bing
    # Whether to include pages in the search results
    # index_pages: true
# Comment plugin configurations
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Comment/
# 评论功能：
comment:
    type: gitalk
    # Gitalk客户端ID，通常由GitHub提供
    client_id: Ov23liifh7QhDzZDzWm0
    # Gitalk客户端密钥，通常由GitHub提供
    client_secret: 9ebd89ad02c6a87ea6ae8b0036ded99acb04ebab
    # GitHub仓库名称，用于存放评论
    repo: Hexo
    # GitHub仓库的所有者，通常是您的GitHub用户名
    owner: RiverBreaker
    # GitHub仓库的管理员列表，您可以指定多个管理员
    admin:
        - RiverBreaker
    # 每页显示的评论数量，默认为15
    per_page: 15                    # 可选填
    # 是否启用无干扰模式，默认为false
    distraction_free_mode: false    # 可选填
    # 评论分页的方向，默认为last（最后）
    pager_direction: last           # 可选填
    # 是否手动创建Issue，默认为false
    create_issue_manually: false    # 可选填
    # 代理设置，可选填
    proxy:                          # 可选填
    # 翻页动画选项，可选填
    flip_move_options:              # 可选填
    # 是否启用快捷键，默认为true
    enable_hotkey: true             # 可选填
    # 语言设置，默认为zh-CN（简体中文）
    language: zh-CN                 # 可选填
# Donate plugin configurations
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Donation/
# donates:
#     # "Afdian.net" donate button configurations
#     -
#         # 爱发电链接
#         # type: afdian
#         # # URL to the "Afdian.net" personal page
#         # url: 'https://afdian.net/u/5247e1a42ec011efb6055254001e7c00'
#     # Alipay donate button configurations
#     -
#         # 支付宝收款码
#         type: alipay
#         # Alipay qrcode image URL
#         qrcode: '/images/alipay.jpg'
#     # "Buy me a coffee" donate button configurations
#     -
#         # 为我买杯咖啡
#         type: buymeacoffee
#         # URL to the "Buy me a coffee" page
#         url: 'https://www.buymeacoffee.com/xiamu'
#     # Patreon donate button configurations
#     # -
#     #     type: patreon
#     #     # URL to the Patreon page
#     #     url: ''
#     # Paypal donate button configurations
#     # -
#     #     type: paypal
#     #     # Paypal business ID or email address
#     #     business: ''
#     #     # Currency code
#     #     currency_code: USD
#     # Wechat donate button configurations
#     -
#         # 微信
#         type: wechat
#         # Wechat qrcode image URL
#         qrcode: '/images/wechat.png'
# Share plugin configurations
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Share/
share:
    type: addtoany
    # URL to the ShareThis share plugin script
    # 分享插件的安装URL，通常为空
    # install_url: ''
# Sidebar configurations.
# Please be noted that a sidebar is only visible when it has at least one widget
sidebar:
    # Left sidebar configurations
    left:
        # 左侧侧边栏是否固定在顶部，true为固定，false为不固定
        # Whether the sidebar sticks to the top when page scrolls
        sticky: false
    # Right sidebar configurations
    right:
        # 右侧侧边栏是否固定在顶部，true为固定，false为不固定
        # Whether the sidebar sticks to the top when page scrolls
        sticky: false
# Sidebar widget configurations
# http://ppoffice.github.io/hexo-theme-icarus/categories/Widgets/
widgets:
    # Profile widget configurations
    # 个人资料小工具配置
    -
        # Where should the widget be placed, left sidebar or right sidebar
        # 小工具应放置的位置，左侧边栏或右侧边栏
        position: left
        # 小工具的类型，这里为个人资料
        type: profile
        # Author name
        # 作者姓名
        author: RiverBreaker
        # Author title
        # 作者头衔
        author_title: Student Developer
        # Author's current location
        # 作者的当前所在地
        ### location: Earth, Solar System ####
        # URL or path to the avatar image
        # 头像图片的URL或路径
        avatar: 
        # Whether show the rounded avatar image
        # 是否显示圆形头像
        avatar_rounded: false
        # Email address for the Gravatar
        # Gravatar的电子邮件地址
        gravatar: 
        # URL or path for the follow button
        # 关注按钮的URL或路径
        follow_link: https://github.com/RiverBreaker
        # Links to be shown on the bottom of the profile widget
        # 个人资料小工具底部显示的社交链接
        social_links:
            Github:
                icon: fab fa-github
                url: https://github.com/RiverBreaker
            Facebook:
                icon: fab fa-facebook
                url: https://facebook.com
            Twitter:
                icon: fab fa-twitter
                url: https://twitter.com
            Dribbble:
                icon: fab fa-dribbble
                url: https://dribbble.com
            RSS:
                icon: fas fa-rss
                url: /
    # Table of contents widget configurations
    # -
    #     # Where should the widget be placed, left sidebar or right sidebar
    #     # 小工具应放置的位置，左侧边栏或右侧边栏
    #     position: left  ## 代码
    #     type: toc  ## 代码
    #     # Whether to show the index of each heading
    #     # 是否显示每个标题的索引
    #     index: true  ## 代码
    #     # Whether to collapse sub-headings when they are out-of-view
    #     # 当子标题超出视图时是否折叠
    #     collapsed: true  ## 代码
    #     # Maximum level of headings to show (1-6)  
    #     # 显示的最大标题级别（1-6）
    #     depth: 3  ## 代码
    # Recommendation links widget configurations
    # 推荐链接小工具配置
    # -
    #     # Where should the widget be placed, left sidebar or right sidebar
    #     # 小工具应放置的位置，左侧边栏或右侧边栏
    #     position: right  ## 代码
    #     type: links  ## 代码
    #     # Names and URLs of the sites
    #     # 站点名称和URL
    #     links:  ## 代码
    #         Hexo: https://hexo.io  ## 代码
    #         Bulma: https://bulma.io  ## 代码
    # Categories widget configurations
    # 分类小工具配置
    -
        # Where should the widget be placed, left sidebar or right sidebar
        # 小工具应放置的位置，左侧边栏或右侧边栏
        position: left
        type: categories
    # Recent posts widget configurations
    # 最新文章小工具配置
    -
        # Where should the widget be placed, left sidebar or right sidebar
        # 小工具应放置的位置，左侧边栏或右侧边栏
        position: right
        type: recent_posts
    # Archives widget configurations
    # 归档小工具配置
    -
        # Where should the widget be placed, left sidebar or right sidebar
        # 小工具应放置的位置，左侧边栏或右侧边栏
        position: right
        type: archives
    # Tags widget configurations
    # 标签小工具配置
    -
        # Where should the widget be placed, left sidebar or right sidebar
        # 小工具应放置的位置，左侧边栏或右侧边栏
        position: left
        type: tags
        # How to order tags. For example 'name' to order by name in ascending order, and '-length' to order by number of posts in each tags in descending order
        # 标签排序方式。例如'name'按名称升序排序，'-length'按每个标签的文章数量降序排序
        order_by: name
        # Amount of tags to show. Will show all if not set.
        # 显示的标签数量。如果未设置，将显示所有标签。
        amount: 
        # Whether to show tags count, i.e. number of posts in the tag.
        # 是否显示标签计数，即标签中的文章数量。
        show_count: true
    # Google FeedBurner email subscription widget configurations
    # Google FeedBurner电子邮件订阅小工具配置
    # -
    #     # Where should the widget be placed, left sidebar or right sidebar
    #     # 小工具应放置的位置，左侧边栏或右侧边栏
    #     position: left  ## 代码
    #     type: subscribe_email  ## 代码
    #     # Hint text under the email input
    #     # 电子邮件输入框下的提示文本
    #     description:   ## 代码
    #     # Feedburner ID  ## 代码
    #     feedburner_id: ''  ## 代码
    # Google AdSense unit configurations
    # Google AdSense单元配置
    # -
    #     # Where should the widget be placed, left sidebar or right sidebar
    #     # 小工具应放置的位置，左侧边栏或右侧边栏
    #     position: left  ## 代码
    #     type: adsense  ## 代码
    #     # AdSense client ID
    #     client_id: ''  ## 代码
    #     # AdSense AD unit ID
    #     slot_id: ''  ## 代码
    # Follow.it email subscription widget configurations
    # Follow.it电子邮件订阅小工具配置
    # -
    #     # Where should the widget be placed, left sidebar or right sidebar
    #     # 小工具应放置的位置，左侧边栏或右侧边栏
    #     position: left  ## 代码
    #     type: followit  ## 代码
    #     # Hint text under the email input
    #     # 电子邮件输入框下的提示文本
    #     description:   ## 代码
    #     # Subscription form action URL
    #     # 订阅表单的Action URL
    #     # # action_url: ''   ## 代码
    #     # Feed claiming verification code
    #     # Feed claiming验证码
    #     # # verification_code: ''  ## 代码
# Plugin configurations
# 插件配置
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/
plugins:
    # Enable page startup animations
    # 启用页面启动动画
    animejs: true
    # Show the "back to top" button
    # 显示“返回顶部”按钮
    back_to_top: true
    # Baidu Analytics plugin settings
    # 百度分析插件设置
    # https://tongji.baidu.com
    baidu_analytics:
        # Baidu Analytics tracking ID
        # 百度分析跟踪ID
        tracking_id: 
    # Bing Webmaster Tools plugin settings
    # 必应网站管理员工具插件设置
    # https://www.bing.com/toolbox/webmaster/
    bing_webmaster:
        # Bing Webmaster Tools tracking ID in the <meta> tag
        # 必应网站管理员工具跟踪ID，用于<meta>标签
        tracking_id: 
    # BuSuanZi site/page view counter
    # 布算子网站/页面浏览计数器
    # https://busuanzi.ibruce.info
    busuanzi: true
    # CNZZ statistics
    # CNZZ统计
    # https://www.umeng.com/web
    cnzz:
        # CNZZ tracker id
        # CNZZ跟踪器ID
        id: 
        # CNZZ website id
        # CNZZ网站ID
        web_id: 
    # Alerting users about the use of cookies
    # 向用户通知使用cookies的插件
    # https://www.osano.com/cookieconsent/
    cookie_consent:
        # The compliance type. Can be "info", "opt-in", or "opt-out"
        # 合规类型。可以是"info"、"opt-in"或"opt-out"
        type: info
        # Theme of the popup. Can be "block", "edgeless", or "classic"
        # 弹出窗口的主题。可以是"block"、"edgeless"或"classic"
        theme: edgeless
        # Whether the popup should stay static regardless of the page scrolls
        # 弹出窗口是否应保持静态，无论页面滚动与否
        static: false
        # Where on the screen the consent popup should display
        # 弹出窗口在屏幕上的位置
        position: bottom-left
        # URL to your site's cookie policy
        # 网站cookie政策的URL
        policyLink: https://www.cookiesandyou.com/
    # Enable the lightGallery and Justified Gallery plugins
    # 启用lightGallery和Justified Gallery插件
    gallery: true
    # Google Analytics plugin settings
    # Google Analytics插件设置
    # https://analytics.google.com
    google_analytics:
        # Google Analytics tracking ID
        # Google Analytics跟踪ID
        tracking_id: 
    # Hotjar user feedback plugin
    # Hotjar用户反馈插件
    # https://www.hotjar.com/
    hotjar:
        # Hotjar site id
        # Hotjar网站ID
        site_id: 
    # Enable the KaTeX math typesetting support
    # 启用KaTeX数学排版支持
    # https://katex.org/
    katex: false
    # Enable the MathJax math typesetting support
    # 启用MathJax数学排版支持
    # https://www.mathjax.org/
    mathjax: false
    # Enable the Outdated Browser plugin
    # 启用Outdated Browser插件
    # http://outdatedbrowser.com/
    outdated_browser: false
    # Enable PJAX
    # 启用PJAX
    pjax: true
    # Show a progress bar at top of the page on page loading
    # 页面加载时在页面顶部显示进度条
    progressbar: true
    # Statcounter statistics
    # Statcounter统计
    # https://statcounter.com/
    statcounter:
        # Statcounter project id
        # Statcounter项目ID
        project: 
        # Statcounter project security code
        # Statcounter项目安全代码
        security: 
    # Twitter conversion tracking plugin settings
    # Twitter转化跟踪插件设置
    # https://business.twitter.com/en/help/campaign-measurement-and-analytics/conversion-tracking-for-websites.html
    twitter_conversion_tracking:
        # Twitter Pixel ID
        # Twitter像素ID
        pixel_id: 
# CDN provider settings
# CDN提供商设置
# https://ppoffice.github.io/hexo-theme-icarus/Configuration/Theme/speed-up-your-site-with-custom-cdn/
providers:
    # Name or URL template of the JavaScript and/or stylesheet CDN provider
    # JavaScript和/或样式表CDN提供商的名称或URL模板
    cdn: jsdelivr
    # Name or URL template of the webfont CDN provider
    # Web字体CDN提供商的名称或URL模板
    fontcdn: google
    # Name or URL of the fontawesome icon font CDN provider
    # FontAwesome图标字体CDN提供商的名称或URL
    iconcdn: fontawesome
